// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgI7c-jibpHUZ099heuWWpxufX0JAbtA8',
    appId: '1:488552846630:web:cb50f59c50559aa9d99de7',
    messagingSenderId: '488552846630',
    projectId: 'tamwenweb',
    authDomain: 'tamwenweb.firebaseapp.com',
    storageBucket: 'tamwenweb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBGNlcZnOWzbZxXshNYsuNQJN498C962s',
    appId: '1:488552846630:android:a7d89d18c60f6ae9d99de7',
    messagingSenderId: '488552846630',
    projectId: 'tamwenweb',
    storageBucket: 'tamwenweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4emU2gfsqe86_CGibvUpQpD9KpEpPE3A',
    appId: '1:488552846630:ios:acb79940f89a5d66d99de7',
    messagingSenderId: '488552846630',
    projectId: 'tamwenweb',
    storageBucket: 'tamwenweb.appspot.com',
    iosClientId: '488552846630-d94g3hcjp4rd57o25p4bs4oteb02k18t.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamwenWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4emU2gfsqe86_CGibvUpQpD9KpEpPE3A',
    appId: '1:488552846630:ios:acb79940f89a5d66d99de7',
    messagingSenderId: '488552846630',
    projectId: 'tamwenweb',
    storageBucket: 'tamwenweb.appspot.com',
    iosClientId: '488552846630-d94g3hcjp4rd57o25p4bs4oteb02k18t.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamwenWeb',
  );
}
